# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import flowchart_pb2 as protos_dot_flowchart__pb2


class FlowchartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunFlowchart = channel.stream_stream(
                '/flowchart.Flowchart/RunFlowchart',
                request_serializer=protos_dot_flowchart__pb2.FlowchartRequest.SerializeToString,
                response_deserializer=protos_dot_flowchart__pb2.FlowchartReply.FromString,
                )


class FlowchartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunFlowchart(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowchartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunFlowchart': grpc.stream_stream_rpc_method_handler(
                    servicer.RunFlowchart,
                    request_deserializer=protos_dot_flowchart__pb2.FlowchartRequest.FromString,
                    response_serializer=protos_dot_flowchart__pb2.FlowchartReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowchart.Flowchart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Flowchart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunFlowchart(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/flowchart.Flowchart/RunFlowchart',
            protos_dot_flowchart__pb2.FlowchartRequest.SerializeToString,
            protos_dot_flowchart__pb2.FlowchartReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
