# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/flowchart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/flowchart.proto\x12\tflowchart\x1a\x19google/protobuf/any.proto\"\xbc\x01\n\x10\x46lowchartRequest\x12\x31\n\x05start\x18\x01 \x01(\x0b\x32 .flowchart.FlowchartStartRequestH\x00\x12\x33\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32!.flowchart.FlowchartCancelRequestH\x00\x12\x35\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\".flowchart.FlowchartControlRequestH\x00\x42\t\n\x07request\"9\n\x15\x46lowchartStartRequest\x12 \n\x02rf\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x18\n\x16\x46lowchartCancelRequest\"P\n\x17\x46lowchartControlRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"G\n\x0e\x46lowchartReply\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any2Y\n\tFlowchart\x12L\n\x0cRunFlowchart\x12\x1b.flowchart.FlowchartRequest\x1a\x19.flowchart.FlowchartReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.flowchart_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FLOWCHARTREQUEST']._serialized_start=65
  _globals['_FLOWCHARTREQUEST']._serialized_end=253
  _globals['_FLOWCHARTSTARTREQUEST']._serialized_start=255
  _globals['_FLOWCHARTSTARTREQUEST']._serialized_end=312
  _globals['_FLOWCHARTCANCELREQUEST']._serialized_start=314
  _globals['_FLOWCHARTCANCELREQUEST']._serialized_end=338
  _globals['_FLOWCHARTCONTROLREQUEST']._serialized_start=340
  _globals['_FLOWCHARTCONTROLREQUEST']._serialized_end=420
  _globals['_FLOWCHARTREPLY']._serialized_start=422
  _globals['_FLOWCHARTREPLY']._serialized_end=493
  _globals['_FLOWCHART']._serialized_start=495
  _globals['_FLOWCHART']._serialized_end=584
# @@protoc_insertion_point(module_scope)
