name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: chartboost/ruff-action@v1
        name: Ruff format check
        with:
          args: format --check .

  python-code-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: chartboost/ruff-action@v1
        name: Ruff linter check

  ts-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: actions/setup-node@v3
        name: Install Node.js 20
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Cache pnpm
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Prettier check
        run: pnpm run check

      - name: TypeScript check
        run: pnpm run typecheck
